In [2]:
 from sklearn.linear_model import LogisticRegression
 from sklearn.svm import SVC
 from sklearn.ensemble import RandomForestClassifier
 import numpy as np
 from sklearn.datasets import load_digits

In [3]:
df=load_digits()

Split into train and testing

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.data,df.target,test_size=0.3)

In [16]:
lr=LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [17]:
svm=SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9907407407407407

In [18]:
rf=RandomForestClassifier()
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9722222222222222

In Train test Split method, SVC has outperformed by barest of marginal/decimals  

Train Test split changes the score as we re run Hence it could be a disadvantage. Hence we can use KFold Method

**KFold Cross Validation**

In [20]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=4)

In [21]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


In [22]:
#KFold in digits dataset

In [23]:
def get_score(model,X_train,X_test,Y_train,Y_test):
  model.fit(X_train,X_test)
  return model.score(X_test,Y_test)

In [24]:
from sklearn.model_selection import StratifiedKFold
fold=StratifiedKFold(n_splits=3)

In [34]:
score_l=[]
score_svm=[]
score_rf=[]
for train_index,test_index in fold.split(df.data):
  X_train,X_test,Y_train,Y_test = df.data[train_index],df.data[test_index],df.target[train_index],df.target[test_index]

  #performance
  score_l.append(get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test))
  score_svm.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))
  score_rf.append(get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test))


TypeError: ignored

Cross Val Score

In [37]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),df.data,df.target)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [38]:
cross_val_score(SVC(),df.data,df.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=100),df.data,df.target)

array([0.94166667, 0.92222222, 0.95821727, 0.95543175, 0.93314763])