In [2]:
 from sklearn.linear_model import LogisticRegression
 from sklearn.svm import SVC
 from sklearn.ensemble import RandomForestClassifier
 import numpy as np
 from sklearn.datasets import load_digits

In [3]:
df=load_digits()

Split into train and testing

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.data,df.target,test_size=0.3)

In [16]:
lr=LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [17]:
svm=SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9907407407407407

In [18]:
rf=RandomForestClassifier()
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9722222222222222

In Train test Split method, SVC has outperformed by barest of marginal/decimals  

Train Test split changes the score as we re run Hence it could be a disadvantage. Hence we can use KFold Method

**KFold Cross Validation**

In [20]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=4)

In [21]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


In [22]:
#KFold in digits dataset

In [23]:
def get_score(model,X_train,X_test,Y_train,Y_test):
  model.fit(X_train,X_test)
  return model.score(X_test,Y_test)

In [24]:
from sklearn.model_selection import StratifiedKFold
fold=StratifiedKFold(n_splits=3)

In [34]:
score_l=[]
score_svm=[]
score_rf=[]
for train_index,test_index in fold.split(df.data):
  X_train,X_test,Y_train,Y_test = df.data[train_index],df.data[test_index],df.target[train_index],df.target[test_index]

  #performance
  score_l.append(get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test))
  score_svm.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))
  score_rf.append(get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test))


TypeError: ignored

Cross Val Score

In [37]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),df.data,df.target)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [38]:
cross_val_score(SVC(),df.data,df.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=100),df.data,df.target)

array([0.94166667, 0.92222222, 0.95821727, 0.95543175, 0.93314763])

Another Dataset usage

In [45]:
import pandas as pd
df=pd.read_csv('data (1).csv')

In [46]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [47]:
X=df.drop(columns='diagnosis',axis=1)
Y=df['diagnosis']

K Fold Cross Validation

In [52]:
#import numpy as np
#from sklearn.tree import DecisionTreeClassifier
#model=DecisionTreeClassifier()
#kfold_validation=KFold(10)
#results=cross_val_score(model,X,Y,cv=kfold_validation)
#print(results)
#print(np.mean(results))

**Stratified K-Fold Cross Validation**

In [53]:
from sklearn.tree import DecisionTreeClassifier

In [54]:
X=df.drop(columns='diagnosis',axis=1)
Y=df['diagnosis']

In [56]:
#from sklearn.model_selection import StratifiedKFold
#skfold=StratifiedKFold(n_splits=5)
#model=DecisionTreeClassifier()
#scores=cross_val_score(model,X,Y,cv=skfold)

In [57]:
#print(np.mean(scores))

**Leave One Out Cross Validation**

In [ ]:
#import numpy as np
#from sklearn.tree import DecisionTreeClassifier
#from sklearn.model_selection import LeaveOneOut
#model=DecisionTreeClassifier()
#leave_val=LeaveOneOut(10)
#results=cross_val_score(model,X,Y,cv=leave_val)
#print(results)
#print(np.mean(results))